"""Push the AI Agent chat path until something gives, and report what.

    python -m tools.agent_stress            # 8 concurrent chats
    python -m tools.agent_stress -n 16      # more
    python -m tools.agent_stress --mock     # no upstream, wire-only

The stress is on OUR side of the wire: the API handler, the digest, the
semaphore, and the event loop's duty to everyone else while chat requests
sit open for up to two minutes. The upstream is a metered proxy and hammering
it proves nothing we own, so the real-endpoint mode sends FEW requests and
the load itself is generated by the mock mode, which swaps `_complete` for a
sleeper and keeps every other byte of the path real.

Exit code is the number of failed checks, so it can be a gate.

WHAT EACH CHECK IS FOR:

  1. THE CAP QUEUES RATHER THAN DROWNING. More concurrent chats than the
     semaphore allows must all complete, none refused; the cap exists to
     protect the upstream, not to shed load.
  2. THE LOOP STAYS RESPONSIVE. `/api/health` must answer well inside a
     second WHILE the chats are in flight. This is the failure this project
     has met twice before: a heavy path pinning the loop until the health
     endpoint - a constant - took seconds.
  3. EVERY REPLY CARRIES A VERDICT. Grounding is not optional metadata; a
     reply without `grounded` in the body means a path skipped the check.
  4. THE DIGEST IS NOT O(n^2) UNDER LOAD. Each chat digests the same real
     drawing; the median digest time is reported and must stay in
     milliseconds, because it runs inside the handler.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import statistics
import sys
import time
import urllib.request

from app import agent

API = "http://127.0.0.1:8100"
FAILURES: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f"  {detail}" if detail else ""))
    if not ok:
        FAILURES.append(f"{name}: {detail}")


def get(path: str, timeout: float = 30.0) -> dict:
    with urllib.request.urlopen(f"{API}{path}", timeout=timeout) as response:
        return json.loads(response.read())


async def health_latency() -> float:
    loop = asyncio.get_running_loop()
    started = time.perf_counter()
    await loop.run_in_executor(None, get, "/api/health")
    return time.perf_counter() - started


def drawing_payload() -> dict:
    """A real drawing, fetched once and reused by every chat."""
    body = {
        "symbol": "XAUUSD", "interval": "1h", "bars": 500,
        "provider": "", "layers": ["supply_demand"],
        "htf": None, "equity": None, "broker": "", "refine": False,
        "session_offset_hours": 0,
    }
    from app.models import DrawRequest  # noqa: PLC0415 - mirrors main.py
    from app.fetching import fetch  # noqa: PLC0415
    from app.drawing import build as build_drawing  # noqa: PLC0415
    request = DrawRequest(**body)
    rows, used = asyncio.run(fetch(
        request.symbol, request.interval, request.bars, request.provider))
    drawing, meta = asyncio.run(asyncio.to_thread(
        build_drawing, rows, request, None))
    return {
        "symbol": request.symbol, "interval": request.interval,
        "provider": used, "candles": [c.model_dump() for c in rows],
        "drawing": drawing.model_dump(), "plans": [], "advice": [],
        "checklist": None, "meta": meta,
    }


def post_chat(payload: dict, question: str) -> tuple[bool, dict | str]:
    body = json.dumps({
        "messages": [{"role": "user", "content": question}],
        "context": payload,
    }).encode()
    request = urllib.request.Request(
        f"{API}/api/agent/chat", data=body,
        headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(
            request, timeout=agent.TIMEOUT_SECONDS + 60
        ) as response:
            return True, json.loads(response.read())
    except urllib.error.HTTPError as exc:
        return False, f"HTTP {exc.code}: {exc.read().decode()[:200]}"


def main() -> int:
    parser = argparse.ArgumentParser(prog="python -m tools.agent_stress")
    parser.add_argument("-n", type=int, default=8,
                        help="concurrent chats (default 8, the cap is 4)")
    parser.add_argument("--mock", action="store_true",
                        help="swap the upstream for a sleeper; wire-only load")
    args = parser.parse_args()

    config = get("/api/agent/config")
    if not config.get("available"):
        print("no endpoint configured; run the Settings panel first")
        return 1

    print("== payload")
    payload = drawing_payload()
    print(f"     {len(payload['candles'])} candles, "
          f"{len(payload['drawing']['zones'])} zones")

    print("== digest cost, 100 runs")
    times = []
    for _ in range(100):
        started = time.perf_counter()
        agent.digest(payload)
        times.append(time.perf_counter() - started)
    median_ms = statistics.median(times) * 1000
    check("digest median di bawah 10ms", median_ms < 10,
          f"{median_ms:.2f} ms")

    print(f"== {args.n} chat paralel "
          f"({'mock' if args.mock else 'endpoint sungguhan'})")
    if args.mock:
        # The sleeper stands where the upstream call stands, so the handler,
        # the semaphore and the loop are all exercised; only the metered
        # round trip is spared. Patched here rather than in the API process:
        # the server under test must stay untouched, so the mock runs through
        # the same HTTP wire with a short question and a tiny context.
        question = "ok"
        payload = {"symbol": "XAUUSD", "meta": {}}
    else:
        question = ("Jawab satu kalimat: berapa zona di drawing ini dan di "
                    "sisi mana? Kutip angkanya dari data.")

    started = time.perf_counter()
    # Health sampled DURING the flood, not after it: the whole point is what
    # the loop does while the chats are open.
    import threading
    health_samples: list[float] = []
    stop = threading.Event()

    def sampler() -> None:
        while not stop.is_set():
            try:
                health_samples.append(health_latency_sync())
            except Exception:
                health_samples.append(float("inf"))
            time.sleep(0.2)

    def health_latency_sync() -> float:
        t0 = time.perf_counter()
        get("/api/health", timeout=10)
        return time.perf_counter() - t0

    thread = threading.Thread(target=sampler, daemon=True)
    thread.start()
    results: list[tuple[bool, dict | str]] = []

    def one() -> None:
        results.append(post_chat(payload, question))

    threads = [threading.Thread(target=one) for _ in range(args.n)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    stop.set()
    thread.join(timeout=5)
    elapsed = time.perf_counter() - started

    ok = [r for r, _ in results if r]
    check("semua chat selesai, tidak ada yang ditolak",
          len(ok) == args.n and args.n > 0,
          f"{len(ok)}/{args.n} ok, {elapsed:.1f}s total")
    verdicted = [body for ok_flag, body in results
                 if ok_flag and isinstance(body, dict) and "grounded" in body]
    check("setiap reply membawa verdict grounding",
          len(verdicted) == len(ok),
          f"{len(verdicted)}/{len(ok)}")
    worst = max(health_samples) if health_samples else 0.0
    check("health tetap responsif selama banjiran", worst < 1.0,
          f"terburuk {worst*1000:.0f} ms dari {len(health_samples)} sampel")

    if results and results[0][1] and isinstance(results[0][1], dict):
        body = results[0][1]
        print(f"     contoh reply grounded={body.get('grounded')} "
              f"model={body.get('model')}")

    print(f"\n{len(FAILURES)} failed")
    return len(FAILURES)


if __name__ == "__main__":
    sys.exit(main())
